services:
  ruby:
    image: ruby:${RUBY_IMAGE:-2.7}-bullseye
    environment:
      HISTFILE: /app/.bash_history
      BUNDLE_PATH: /bundle
      BUNDLE_CONFIG: /app/.bundle/config
      DATABASE_URL: postgres://postgres:@postgres:5432
      ELASTICSEARCH_URL: http://elasticsearch:9200
    command: bash
    working_dir: /app
    volumes:
      - .:/app:cached
      - bundler_data:/bundle
    tmpfs:
      - /tmp
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 10s

  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: -Xms64m -Xmx256m
      discovery.type: single-node
      http.cors.enabled: "true"
      bootstrap.memory_lock: "true"
    healthcheck:
      test: curl --silent --fail 0.0.0.0:9200/_cluster/health
      interval: 30s

volumes:
  bundler_data:
